# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

samplingPercent: 100
rowFilter:
rules:
  - column: age
    dimension: COMPLETENESS
    name: non-null
    description: non-null column
    threshold: 1.0
    non_null_expectation: {}
  - column: balance
    dimension: COMPLETENESS
    name: non-null
    description: non-null column
    threshold: 1.0
    non_null_expectation: {}
  - column: education
    dimension: COMPLETENESS
    name: non-null
    description: non-null column
    threshold: 1.0
    non_null_expectation: {}
  - column: education
    dimension: VALIDITY
    name: one-of-set-education
    description: rule for values in a set
    ignore_null: false
    set_expectation:
      values:
      - secondary
      - tertiary
      - primary
      - unknown
  - column: education
    dimension: VALIDITY
    name: not-valid-education
    description:  rule for sql query
    tableConditionExpectation:
      sqlExpression: (LENGTH(`education`) >= 7 AND LENGTH(`education`) <= 9) OR `education` IS NULL
  - column: job
    dimension: COMPLETENESS
    name: non-null
    description: non-null column
    threshold: 1.0
    non_null_expectation: {}
  - column: job
    dimension: VALIDITY
    name: one-of-set-job
    description: rule for values in a set
    ignore_null: false
    set_expectation:
      values:
      - management
      - technician
      - blue-collar
      - admin.
      - retired
      - services
      - self-employed
      - unemployed
      - student
      - entrepreneur
  - column: job
    dimension: VALIDITY
    name: not-valid-job
    description:  rule for sql query
    tableConditionExpectation:
      sqlExpression: (LENGTH(`job`) >= 6 AND LENGTH(`job`) <= 13) OR `job` IS NULL
  - column: loan
    dimension: COMPLETENESS
    name: non-null-loan
    description: non-null column
    threshold: 1.0
    non_null_expectation: {}
  - column: loan
    dimension: VALIDITY
    name: one-of-set-loan
    description: rule for values in a set
    ignore_null: false
    set_expectation:
      values:
      - true
      - false
  - dimension: VALIDITY
    name: not-empty-table
    description: Sample rule for a non-empty table
    tableConditionExpectation:
      sqlExpression: COUNT(*) > 0
